# ==============================================================================
# SERVICE: SimpleLogin
# DESCRIPTION: 
#
#
#
# ==============================================================================
#
services:
  sl-db:
    image: postgres:12.1
    container_name: sl-db
    environment:
      POSTGRES_PASSWORD: ${SL_DB_PASSWORD}
      POSTGRES_USER: ${SL_DB_USER}
      POSTGRES_DB: ${SL_DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ${STACK_DIR}/db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - sl-network

  sl-migration:
    image: &sl-image simplelogin/app:4.6.5-beta
    container_name: sl-migration
    env_file: ${STACK_DIR}/simplelogin.env
    command: ["alembic", "upgrade", "head"]
    volumes:
      - ${STACK_DIR}/pgp:/sl/pgp
      - ${STACK_DIR}/upload:/code/static/upload
      - ${STACK_DIR}/dkim.key:/dkim.key
      - ${STACK_DIR}/dkim.pub.key:/dkim.pub.key
    networks:
      - sl-network
    depends_on:
      sl-db:
        condition: service_healthy

  sl-init:
    image: *sl-image #
    container_name: sl-init
    env_file: ${STACK_DIR}/simplelogin.env
    command: ["python", "init_app.py"]
    volumes:
      - ${STACK_DIR}/pgp:/sl/pgp
      - ${STACK_DIR}/upload:/code/static/upload
      - ${STACK_DIR}/dkim.key:/dkim.key
      - ${STACK_DIR}/dkim.pub.key:/dkim.pub.key
    networks:
      - sl-network
    depends_on:
      sl-migration:
        condition: service_completed_successfully

  sl-app:
    image: *sl-image
    container_name: sl-app
    env_file: ${STACK_DIR}/simplelogin.env
    ports:
      - "127.0.0.1:7777:7777"
    volumes:
      - ${STACK_DIR}/pgp:/sl/pgp
      - ${STACK_DIR}/upload:/code/static/upload
      - ${STACK_DIR}/dkim.key:/dkim.key
      - ${STACK_DIR}/dkim.pub.key:/dkim.pub.key
    restart: unless-stopped
    networks:
      - sl-network
    depends_on:
      sl-init:
        condition: service_completed_successfully

  sl-email:
    image: *sl-image
    container_name: sl-email
    env_file: ${STACK_DIR}/simplelogin.env
    command: ["python", "email_handler.py"]
    ports:
      - "127.0.0.1:20381:20381"
    volumes:
      - ${STACK_DIR}/pgp:/sl/pgp
      - ${STACK_DIR}/upload:/code/static/upload
      - ${STACK_DIR}/dkim.key:/dkim.key
      - ${STACK_DIR}/dkim.pub.key:/dkim.pub.key
    restart: unless-stopped
    networks:
      - sl-network
    depends_on:
      sl-init:
        condition: service_completed_successfully

  sl-job-runner:
    image: *sl-image
    container_name: sl-job-runner
    env_file: ${STACK_DIR}/simplelogin.env    
    command: ["python", "job_runner.py"]
    volumes:
      - ${STACK_DIR}/pgp:/sl/pgp
      - ${STACK_DIR}/upload:/code/static/upload
      - ${STACK_DIR}/dkim.key:/dkim.key
      - ${STACK_DIR}/dkim.pub.key:/dkim.pub.key
    restart: unless-stopped
    networks:
      - sl-network
    depends_on:
      sl-init:
        condition: service_completed_successfully

networks:
  sl-network:
    external: true
